name: Reusable Pattern - Extended
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Unit Tests?: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
  Java-Pipeline:
    needs: Checkout
    uses: iswilliams/Workshop_B/.github/workflows/java_template.yml@main

  Java-Test:
    needs: Checkout
    uses: iswilliams/Workshop_B/.github/workflows/tasks_java_test.yml@main

  Java-Sonar:
    needs: Java-Test
    uses: iswilliams/Workshop_B/.github/workflows/tasks_java_sonarqube.yml@main

  Java-Build:
    needs: Java-Sonar
    uses: iswilliams/Workshop_B/.github/workflows/tasks_java_build.yml@main
