name: Passing Parameters to reusable pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  parameters:
    uses: iswilliams/Workshop_B/.github/workflows/task_with_parameters.yml@main
    with:
      config-path: test
    secrets:
      token: someSecret
